# specific params for cut
lambda_GAN: 1.0
lambda_NCE: 1.0
nce_idt: True
nce_layers: '0,1,2,3,4,5,6'
nce_includes_all_negatives_from_minibatch: False
netF: 'mlp_sample'
netF_nc: 256
nce_T: 0.07 
num_patches: 256 
flip_equivariance: False