# deafult path
checkpoints_dir: './checkpoints'
# model params
model: 'cut'
input_nc: 3
output_nc: 3
ngf: 64
ndf: 64
netD: 'basic'
netG: 'resnet_9blocks'
n_layers_D: 3
normG: 'instance'
normD: 'instance'
init_type: 'xavier'
init_gain: 0.02
no_dropout: True
no_antialias: False
no_antialias_up: False 
# data params
dataset_mode: 'unaligned'
direction: 'AtoB'
serial_batches: True
batch_size: 1
load_size: 286
crop_size: 256
max_dataset_size: 1000000
preprocess: 'resize_and_crop'
no_flip: true
display_winsize: 256
random_scale_max: 3.0
epoch: 'latest'

# train params
start_epoch: 0
n_epochs: 200
n_epochs_decay: 200
beta1: 0.5
beta2: 0.999
lr: 0.0002
gan_mode: 'lsgan'
pool_size: 50
lr_policy: 'linear'
lr_decay_iters: 50
weighted: False
prob_weighted: False

# resume or load model params
epoch: 'latest'
verbose: False
continue_train: False
pretrained_name: None

# visualize params
display_freq: 400 
print_freq: 100
save_epoch_freq: 5 
evaluation_freq: 5000
save_by_iter: False
epoch_count: 1

# extra params
stylegan2_G_num_downsampling: 1
